version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: products
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "cluster.name=cluster-1"
      - "node.name=node-1"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "bootstrap.memory_lock=true"
      - "xpack.security.enabled=false"
      - "ELASTIC_USERNAME=sammi"
      - "ELASTIC_PASSWORD=sammi"
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  elastichq:
    image: "elastichq/elasticsearch-hq"
    ports:
      - "5000:5000"
    depends_on:
      - "elasticsearch"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  nats:
    image: nats
    restart: always
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"

volumes:
  elasticsearch_data:
    driver: local
